[package]
name = "sapphire"
version = "0.1.0"
edition = "2024"
authors = ["Alexander Knott <alexander.knott@posteo.de>"]
description = "A declarative system management suite for macOS"

[dependencies]
anyhow = "1.0.96"
assert_cmd = "2.0.16"
assert_fs = "1.1.2"
chrono = { version = "0.4.35", features = ["serde"] }
clap = { version = "4.5.31", features = ["derive"] }
console = "0.15.10"
dialoguer = "0.11.0"
directories = "6.0.0"
indicatif = "0.17.11"
lazy_static = "1.4.0"
predicates = "3.1.3"
regex = "1.10.4"
serde = { version = "1.0.218", features = ["derive"] }
serde_yaml = "0.9.34"
shellexpand = "3.1.0"
tempfile = "3.17.1"
thiserror = "2.0.11"
toml = "0.8.20"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
dirs = "5.0.1"
