# Compact package manifest example
# This format is even more concise and similar to what the user asked for

[metadata]
description = "Super compact package manifest example"
version = "0.1.0"

# List of taps as simple strings
taps = [
    "homebrew/cask-fonts",
    "homebrew/cask-versions"
]

# List of formulae (CLI tools)
# You can use either the array syntax or the compact list syntax with semicolons
formulae = [
    "fish",
    "neovim",
    "htop:latest",
    "git",
    "ripgrep",
    "fd"
]

# Alternative syntax for brews (GUI apps)
brews = [
    "rectangle",
    "visual-studio-code",
    "firefox",
    "google-chrome"
] 